In [1]:
import cv2,numpy

In [2]:
cap=cv2.VideoCapture(0)

In [3]:
img=numpy.zeros((600,1000,3))

In [4]:
img[:200, 200: ]=[0,100,0]
img[200: 401, 200:]=[255,255,255]
img[400: , 200: ]=[0,0,0]
img[ : , : 201]=[0,0,255]

In [5]:
UAE_flag=img

In [6]:
cv2.imshow("myimage",UAE_flag)
cv2.waitKey()
cv2.destroyAllWindows()

In [32]:
UAE_flag

array([[[  0.,   0., 255.],
        [  0.,   0., 255.],
        [  0.,   0., 255.],
        ...,
        [  0., 100.,   0.],
        [  0., 100.,   0.],
        [  0., 100.,   0.]],

       [[  0.,   0., 255.],
        [  0.,   0., 255.],
        [  0.,   0., 255.],
        ...,
        [  0., 100.,   0.],
        [  0., 100.,   0.],
        [  0., 100.,   0.]],

       [[  0.,   0., 255.],
        [  0.,   0., 255.],
        [  0.,   0., 255.],
        ...,
        [  0., 100.,   0.],
        [  0., 100.,   0.],
        [  0., 100.,   0.]],

       ...,

       [[  0.,   0., 255.],
        [  0.,   0., 255.],
        [  0.,   0., 255.],
        ...,
        [  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [  0.,   0.,   0.]],

       [[  0.,   0., 255.],
        [  0.,   0., 255.],
        [  0.,   0., 255.],
        ...,
        [  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [  0.,   0.,   0.]],

       [[  0.,   0., 255.],
        [  0.,   0., 255.],
        [  0.,  

In [7]:
MOS=cv2.imread('man-of-steel.jpg')

In [41]:
SH=cv2.imread('shazam.jpg')

In [42]:
Shaz=SH

In [9]:
MOS

array([[[81, 68, 24],
        [78, 65, 21],
        [74, 61, 17],
        ...,
        [ 6,  1,  0],
        [ 6,  1,  0],
        [ 6,  1,  0]],

       [[80, 67, 23],
        [78, 65, 21],
        [75, 62, 18],
        ...,
        [ 6,  1,  0],
        [ 6,  1,  0],
        [ 6,  1,  0]],

       [[79, 66, 20],
        [79, 66, 20],
        [77, 64, 20],
        ...,
        [ 6,  1,  0],
        [ 6,  1,  0],
        [ 6,  1,  0]],

       ...,

       [[ 6,  1,  0],
        [ 7,  2,  1],
        [ 7,  2,  1],
        ...,
        [32, 23, 13],
        [32, 23, 13],
        [32, 23, 13]],

       [[ 6,  1,  0],
        [ 7,  2,  1],
        [ 7,  2,  1],
        ...,
        [29, 20, 10],
        [30, 21, 11],
        [30, 21, 11]],

       [[ 6,  1,  0],
        [ 7,  2,  1],
        [ 7,  2,  1],
        ...,
        [27, 18,  8],
        [29, 20, 10],
        [30, 21, 11]]], dtype=uint8)

In [45]:
Shaz.shape

(628, 1000, 3)

In [44]:
Shaz=Shaz[:628 ,200:1200]

In [23]:
MOS.shape

(628, 1000, 3)

In [21]:
SH.shape

(628, 1000, 3)

In [20]:
SH=SH[:628 ,200:1200]

In [22]:
MOS=MOS[:628 ,200:1200]

In [40]:
cv2.imshow("myimage",Shaz)
cv2.waitKey()
cv2.destroyAllWindows()

In [47]:
cv2.imshow("myimage",MOS)
cv2.waitKey()
cv2.destroyAllWindows()

In [162]:
MOS

array([[[28, 18,  8],
        [28, 18,  8],
        [28, 18,  8],
        ...,
        [ 6,  1,  0],
        [ 6,  1,  0],
        [ 6,  1,  0]],

       [[29, 19,  9],
        [28, 18,  8],
        [28, 18,  8],
        ...,
        [ 6,  1,  0],
        [ 6,  1,  0],
        [ 6,  1,  0]],

       [[29, 19,  9],
        [29, 19,  9],
        [28, 18,  8],
        ...,
        [ 6,  1,  0],
        [ 6,  1,  0],
        [ 6,  1,  0]],

       ...,

       [[ 7,  2,  1],
        [ 7,  2,  1],
        [ 7,  2,  1],
        ...,
        [32, 23, 13],
        [32, 23, 13],
        [32, 23, 13]],

       [[ 7,  2,  1],
        [ 7,  2,  1],
        [ 7,  2,  1],
        ...,
        [29, 20, 10],
        [30, 21, 11],
        [30, 21, 11]],

       [[ 7,  2,  1],
        [ 7,  2,  1],
        [ 7,  2,  1],
        ...,
        [27, 18,  8],
        [29, 20, 10],
        [30, 21, 11]]], dtype=uint8)

In [26]:
Crop_sha=SH[10:265,610:790]

In [27]:
Crop_Sup=MOS[45:300,320:500]

In [28]:
cv2.imshow("Shazam",Crop_sha)
cv2.waitKey()
cv2.destroyAllWindows()

In [29]:
cv2.imshow("SuperMan", Crop_Sup)
cv2.waitKey()
cv2.destroyAllWindows()

In [30]:
Crop_Sup.shape

(255, 180, 3)

In [32]:
SH[10:265,610:790]=MOS[45:300,320:500]

In [46]:
MOS[45:300,320:500]=Shaz[10:265,610:790]

In [181]:
Crop_SH=cv2.imread

In [31]:
Crop_sha.shape

(255, 180, 3)

In [41]:
MOS.shape

(628, 1000, 3)

In [64]:
Shaz.shape

(628, 1000, 3)