In [1]:
import cv2,numpy

In [56]:
cap=cv2.VideoCapture(0)

In [4]:
ret, photo=cap.read()

In [5]:
ret

True

In [6]:
photo

array([[[124, 143, 154],
        [124, 143, 154],
        [123, 142, 153],
        ...,
        [135, 173, 167],
        [134, 175, 168],
        [135, 176, 169]],

       [[123, 142, 153],
        [123, 142, 153],
        [123, 142, 153],
        ...,
        [135, 173, 167],
        [135, 176, 169],
        [135, 176, 169]],

       [[117, 143, 149],
        [119, 143, 149],
        [120, 144, 150],
        ...,
        [136, 174, 168],
        [137, 175, 169],
        [138, 176, 170]],

       ...,

       [[103,  80,  64],
        [104,  82,  70],
        [102,  82,  71],
        ...,
        [ 89,  81,  58],
        [ 85,  79,  56],
        [ 83,  77,  54]],

       [[109,  84,  74],
        [107,  81,  75],
        [103,  78,  74],
        ...,
        [ 85,  81,  57],
        [ 83,  79,  55],
        [ 80,  76,  52]],

       [[108,  83,  73],
        [104,  78,  72],
        [100,  75,  71],
        ...,
        [ 83,  79,  55],
        [ 80,  76,  52],
        [ 77,  73,  49]]

In [7]:
cv2.imwrite("my.jpg", photo)

True

In [8]:
cap.release()

In [76]:
cv2.imshow("myimage", cn)
cv2.waitKey()
cv2.destroyAllWindows()

In [11]:
p1=cv2.imread('my.jpg')

In [12]:
p1

array([[[123, 143, 154],
        [123, 143, 154],
        [123, 144, 152],
        ...,
        [135, 173, 167],
        [134, 175, 168],
        [135, 176, 169]],

       [[122, 142, 153],
        [122, 143, 151],
        [122, 143, 151],
        ...,
        [135, 173, 167],
        [137, 175, 169],
        [136, 177, 170]],

       [[119, 142, 150],
        [120, 144, 150],
        [120, 144, 150],
        ...,
        [137, 175, 169],
        [137, 175, 169],
        [138, 176, 170]],

       ...,

       [[102,  80,  68],
        [104,  82,  70],
        [102,  82,  71],
        ...,
        [ 87,  81,  58],
        [ 85,  80,  55],
        [ 83,  78,  53]],

       [[107,  85,  74],
        [104,  81,  73],
        [101,  79,  73],
        ...,
        [ 86,  80,  57],
        [ 83,  79,  54],
        [ 80,  76,  51]],

       [[107,  84,  76],
        [101,  78,  70],
        [ 98,  76,  71],
        ...,
        [ 84,  78,  55],
        [ 80,  76,  51],
        [ 78,  74,  49]]

In [17]:
p1.shape

(480, 640, 3)

In [35]:
p1[-200:200]=[255,255,0]

In [27]:
p1[240]

array([[255, 255,   0],
       [255, 255,   0],
       [255, 255,   0],
       ...,
       [255, 255,   0],
       [255, 255,   0],
       [255, 255,   0]], dtype=uint8)

In [47]:
cn=numpy.zeros((560,1000,3))

In [48]:
cn.shape

(560, 1000, 3)

In [49]:
cn[: 280]=[0,254,255]

In [71]:
while True:
    ret1, photo=cap.read()
    cphoto=cv2.cvtColor(photo,cv2.COLOR_BGR2GRAY)
    cv2.imshow('hi', cphoto)
    if cv2.waitKey(10)== 13:
        break
cv2.destroyAllWindows()

In [72]:
cn

array([[[  0., 254., 255.],
        [  0., 254., 255.],
        [  0., 254., 255.],
        ...,
        [  0., 254., 255.],
        [  0., 254., 255.],
        [  0., 254., 255.]],

       [[  0., 254., 255.],
        [  0., 254., 255.],
        [  0., 254., 255.],
        ...,
        [  0., 254., 255.],
        [  0., 254., 255.],
        [  0., 254., 255.]],

       [[  0., 254., 255.],
        [  0., 254., 255.],
        [  0., 254., 255.],
        ...,
        [  0., 254., 255.],
        [  0., 254., 255.],
        [  0., 254., 255.]],

       ...,

       [[  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [  0.,   0.,   0.],
        ...,
        [  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [  0.,   0.,   0.]],

       [[  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [  0.,   0.,   0.],
        ...,
        [  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [  0.,   0.,   0.]],

       [[  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [  0.,  

In [73]:
cap.release()

In [2]:
Superman=cv2.imread('man-of-steel.jpg')

In [3]:
Shazam=cv2.imread('shazam.jpg')

In [6]:
Sup.shape

(628, 1000, 3)

In [7]:
SH.shape

(628, 1000, 3)

In [4]:
SH=Shazam[:628 ,200:1200]

In [5]:
Sup=Superman[:628 ,200:1200]

In [8]:
Combined= numpy.hstack((SH,Sup))

In [9]:
cv2.imshow("myimage", Combined)
cv2.waitKey()
cv2.destroyAllWindows()